devtools:
  livereload:
    enabled: true
    port: 8080
  restart:
    enabled: true

spring:
  resources:
    static-locations: classpath:/template/
  datasource:
    username: root
    password: a1241639333
    url:  jdbc:mysql://localhost:3306/world?



